#!/usr/bin/python3
"""
Fsk App that integrates with AirBnB static HTML Template
"""
import uuid
from models import storage
from models.state import State
from models.city import City
from models.amenity import Amenity
from models.place import Place
from os import environ
from flask import Flask, render_template

app = Flask(__name__)
app.url_map.strict_slashes = False


def get_data():
    state_objs = storage.all('State').values()
    states = {state.name: state for state in state_objs}
    amenities = storage.all('Amenity').values()
    places = storage.all('Place').values()
    users = {user.id: f"{user.first_name} {user.last_name}" for user in storage.all('User').values()}
    return states, amenities, places, users


@app.route('/1-hbnb')
def hbnb_filters():
    """Handles request to custom template with states, cities & amenities"""
    states, amenities, places, users = get_data()
    return render_template('1-hbnb.html',
                           cache_id=uuid.uuid4(),
                           states=states,
                           amens=amenities,
                           places=places,
                           users=users)


# Flask app runner
if __name__ == "__main__":
    """Main Flask App"""
    app.run(host='0.0.0.0', port=5000)
